name: Detect new PyPI projects

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

env:
  FORCE_COLOR: 1

permissions:
  issues: write

jobs:
  detect_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Run monitor script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/detect_projects.py
